using TaskManagerPro.Blazor.Domain.Common;
using TaskManagerPro.Blazor.Domain.Enums;

namespace TaskManagerPro.Blazor.Domain.Entities;

/// <summary>
/// Core aggregate root of the domain. Represents a unit of work assigned to a user,
/// with lifecycle tracked through status transitions and optional deadline enforcement.
/// </summary>
public class TaskItem : BaseEntity
{
    private WorkTaskStatus _status = WorkTaskStatus.Pending;
    private DateTime? _dueDate;

    /// <summary>Required by EF Core for materialisation. Not intended for direct use.</summary>
    private TaskItem() { }

    /// <summary>
    /// Creates a new task with all mandatory fields. Status defaults to Pending
    /// because a freshly created task has not been started yet.
    /// </summary>
    public TaskItem(string title, string description, DateTime? dueDate, TaskPriority priority, Guid userId)
    {
        Title = title;
        Description = description;
        _dueDate = dueDate;
        Priority = priority;
        UserId = userId;
        _status = WorkTaskStatus.Pending;
    }

    /// <summary>Short human-readable label for the task.</summary>
    public string Title { get; private set; } = string.Empty;

    /// <summary>Detailed explanation of what the task entails.</summary>
    public string Description { get; private set; } = string.Empty;

    /// <summary>
    /// Optional deadline. EF Core writes via _dueDate backing field;
    /// exposed as readonly to prevent arbitrary mutation from outside the aggregate.
    /// </summary>
    public DateTime? DueDate => _dueDate;

    /// <summary>Urgency level used for sorting and visual prominence in the UI.</summary>
    public TaskPriority Priority { get; private set; } = TaskPriority.Medium;

    /// <summary>
    /// Lifecycle state of the task. EF Core writes via _status backing field;
    /// transitions are driven exclusively by Application layer commands.
    /// </summary>
    public WorkTaskStatus Status => _status;

    /// <summary>Foreign key to the owning user.</summary>
    public Guid UserId { get; private set; }

    /// <summary>Navigation property to the owning user.</summary>
    public AppUser? User { get; set; }

    /// <summary>Atomic steps that together fulfil this task.</summary>
    public IReadOnlyCollection<SubTask> SubTasks { get; set; } = new List<SubTask>();

    /// <summary>Checkpoints that track progress toward completing this task.</summary>
    public IReadOnlyCollection<Milestone> Milestones { get; set; } = new List<Milestone>();

    /// <summary>Notifications generated by events on this task.</summary>
    public IReadOnlyCollection<Notification> Notifications { get; set; } = new List<Notification>();

    /// <summary>
    /// Updates mutable fields. Centralised here so the Application layer cannot
    /// scatter property mutations across multiple handlers.
    /// </summary>
    public void Update(string title, string description, DateTime? dueDate, TaskPriority priority)
    {
        Title = title;
        Description = description;
        _dueDate = dueDate;
        Priority = priority;
    }
}
