using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using TaskManagerPro.Blazor.Domain.Common;
using TaskManagerPro.Blazor.Domain.Entities;
using TaskManagerPro.Blazor.Infrastructure.Identity;
using TaskManagerPro.Blazor.Infrastructure.Persistence.Configurations;

namespace TaskManagerPro.Blazor.Infrastructure.Persistence.Context;

/// <summary>
/// Single EF Core DbContext for the application. Inherits from IdentityDbContext
/// so Identity tables and Domain tables share the same database and transaction scope.
/// UpdatedAt is stamped automatically on every save via the EF Core change tracker
/// so command handlers never need to manage the audit timestamp manually.
/// </summary>
public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
{
    /// <inheritdoc />
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }

    /// <summary>Task aggregate roots.</summary>
    public DbSet<TaskItem> Tasks => Set<TaskItem>();

    /// <summary>Subtasks belonging to tasks.</summary>
    public DbSet<SubTask> SubTasks => Set<SubTask>();

    /// <summary>Milestones associated with tasks.</summary>
    public DbSet<Milestone> Milestones => Set<Milestone>();

    /// <summary>User notifications generated by domain events.</summary>
    public DbSet<Notification> Notifications => Set<Notification>();

    /// <summary>Domain users, separate from Identity users.</summary>
    public DbSet<AppUser> AppUsers => Set<AppUser>();

    /// <inheritdoc />
    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);

        builder.ApplyConfiguration(new TaskItemConfiguration());
        builder.ApplyConfiguration(new SubTaskConfiguration());
        builder.ApplyConfiguration(new MilestoneConfiguration());
        builder.ApplyConfiguration(new NotificationConfiguration());
        builder.ApplyConfiguration(new AppUserConfiguration());

        // Map _updatedAt backing field for all BaseEntity-derived types so EF Core
        // can hydrate UpdatedAt on reads without requiring a public or internal setter.
        foreach (var entityType in builder.Model.GetEntityTypes()
            .Where(e => typeof(BaseEntity).IsAssignableFrom(e.ClrType)))
        {
            builder.Entity(entityType.ClrType)
                .Property(nameof(BaseEntity.UpdatedAt))
                .UsePropertyAccessMode(PropertyAccessMode.Field);
        }
    }

    /// <summary>
    /// Stamps UpdatedAt on every modified BaseEntity by writing through EF Core's
    /// change tracker so the backing field is reached without any public setter.
    /// </summary>
    public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        DateTime utcNow = DateTime.UtcNow;

        foreach (var entry in ChangeTracker.Entries<BaseEntity>())
        {
            if (entry.State == EntityState.Modified)
            {
                entry.Property(nameof(BaseEntity.UpdatedAt)).CurrentValue = utcNow;
            }
        }

        return await base.SaveChangesAsync(cancellationToken);
    }
}
